name: Deploy to EC2 Tomcat

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy WAR to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build WAR with Maven
        run: mvn clean package -DskipTests

      - name: Copy WAR to EC2 via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: target/ROOT.war
          target: ${{ secrets.EC2_WAR_DESTINATION }}

      - name: Restart Tomcat on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl restart tomcat10
