name: Deploy to EC2 Tomcat

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy WAR to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: Sombras
        run: mvn clean package -DskipTests

      - name: Verify WAR file existence
        run: |
          ls -l Sombras/target

      - name: Upload WAR to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: Sombras/target/Sombras-0.0.1-SNAPSHOT.war
          target: /home/${{ secrets.EC2_USER }}/ROOT.war
          strip_components: 1

      - name: Move WAR to Tomcat and cleanup old ROOT
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo rm -r /var/lib/tomcat10/webapps/ROOT.war
            sudo rm -r /var/lib/tomcat10/webapps/ROOT
            sudo mv /home/${{ secrets.EC2_USER }}/ROOT.war /var/lib/tomcat10/webapps/ROOT.war
            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/ROOT.war
            sudo chmod 755 /var/lib/tomcat10/webapps/ROOT.war
            sudo systemctl restart tomcat10
